#!/bin/bash
set -e

# ════════════════════════════════════════════════════════════
# OpenCode devbox — boot script
#
# Goal: when you `railway ssh` into this service and type `opencode`,
# you drop straight into the OpenCode TUI, with your auth, sessions, and
# repos preserved across redeploys. Everything persistent lives on the
# /workspace volume; symlinks make OpenCode and git find it in the usual
# home-directory paths.
# ════════════════════════════════════════════════════════════

# ── Volume layout ───────────────────────────────────────────
mkdir -p /workspace/opencode/data \
         /workspace/opencode/config \
         /workspace/repos \
         /workspace/.ssh \
         /workspace/logs
chmod 700 /workspace/.ssh

# OpenCode stores auth (auth.json) + state under ~/.local/share/opencode
# and config under ~/.config/opencode. Point both at the volume so an
# `opencode auth login` survives redeploys.
mkdir -p /root/.local/share /root/.config
ln -sfn /workspace/opencode/data   /root/.local/share/opencode
ln -sfn /workspace/opencode/config /root/.config/opencode
ln -sfn /workspace/.ssh            /root/.ssh

# ── Git / SSH bootstrap ─────────────────────────────────────
# Generate an ed25519 key on first boot (persists via the volume).
if [ ! -f /workspace/.ssh/id_ed25519 ]; then
    echo "[boot] generating ed25519 git key (first boot)..."
    ssh-keygen -t ed25519 -C "opencode-devbox@$(hostname)" \
        -f /workspace/.ssh/id_ed25519 -N "" -q
fi
chmod 600 /workspace/.ssh/id_ed25519 2>/dev/null || true
chmod 644 /workspace/.ssh/id_ed25519.pub 2>/dev/null || true

if ! grep -q "^github.com" /workspace/.ssh/known_hosts 2>/dev/null; then
    echo "[boot] trusting github.com host keys..."
    ssh-keyscan -t rsa,ecdsa,ed25519 github.com 2>/dev/null \
        >> /workspace/.ssh/known_hosts || true
    chmod 644 /workspace/.ssh/known_hosts
fi

git config --global init.defaultBranch main 2>/dev/null || true
[ -n "$GIT_USER_EMAIL" ] && git config --global user.email "$GIT_USER_EMAIL" 2>/dev/null || true
[ -n "$GIT_USER_NAME" ]  && git config --global user.name  "$GIT_USER_NAME"  2>/dev/null || true

# gh auth — re-run each boot if GITHUB_TOKEN is provided.
if [ -n "$GITHUB_TOKEN" ] && command -v gh >/dev/null 2>&1; then
    if ! gh auth status >/dev/null 2>&1; then
        echo "[boot] authenticating gh CLI from GITHUB_TOKEN..."
        echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null \
            || echo "[boot] gh auth login failed (token may be invalid)"
    fi
fi

# ── Provider keys into SSH login shells ─────────────────────
# `railway ssh` opens a login shell; mirror selected Railway variables into
# /etc/profile.d so OpenCode sees your provider keys the moment you type
# `opencode`. (You can also run `opencode auth login` to store them on the
# volume instead.)
echo "[boot] writing /etc/profile.d/00-opencode-env.sh for SSH shells..."
{
    echo "# Auto-generated by entrypoint.sh on each boot."
    for var in ANTHROPIC_API_KEY OPENAI_API_KEY OPENROUTER_API_KEY GITHUB_TOKEN; do
        val="${!var:-}"
        [ -n "$val" ] && printf 'export %s=%q\n' "$var" "$val"
    done
    # Land in your repos directory on login.
    echo 'cd /workspace/repos 2>/dev/null || true'
} > /etc/profile.d/00-opencode-env.sh
chmod 644 /etc/profile.d/00-opencode-env.sh

echo "[boot] ready. Run:  railway ssh   then type:  opencode"
exec "$@"
